### ISSUE TITLE
Update dependencies, high vulnerability ⚠️

### ISSUE THREAD

**Issue by angelhdzmultimedia** [mongodb-js/connect-mongodb-session#110]
I cloned the repo, and bumped all packages to latest versions.

Then tried to run the scripts for the tests, but none of the works. No errors, no output.

Tests are running `mocha` and mocha is successfully installed.

I installed deps with `npm` .

And because I'm on Windows and there's no `env` command, replaced with `set`.

![image](https://github.com/mongodb-js/connect-mongodb-session/assets/10191085/bc1c752e-d336-4f0f-b14a-7c5a5356ed0d)

Now what?

**Comment by angelhdzmultimedia** [comment]
### Update

I just the same thing with https://github.com/expressjs/session
and I achieved to run the tests! :)

**Comment by boly38** [comment]
hi @angelhdzmultimedia

I'm not maintainer but user too and this dep embeeds today a high vulnerability following `npm audit` advice

to improve this existing issue, I would suggest you to insist on the fact that current dependency tree includes HIGH vulnerability from `fast-xml-parser@4.0.11` : for example reword your issue title with `high vuln` somewhere

----

On my side, for example I have on my project :
````
# npm audit report

fast-xml-parser  <=4.2.3
Severity: high
fast-xml-parser vulnerable to Regex Injection via Doctype Entities - https://github.com/advisories/GHSA-6w63-h3fj-q4vw
fast-xml-parser vulnerable to Prototype Pollution through tag or attribute name - https://github.com/advisories/GHSA-x3cc-x39p-42qx
fix available via `npm audit fix`

-----

npm list fast-xml-parser
(...)
└─┬ connect-mongodb-session@3.1.1
  └─┬ mongodb@4.17.1
    └─┬ @aws-sdk/credential-providers@3.245.0
      └─┬ @aws-sdk/client-sts@3.245.0
        └── fast-xml-parser@4.0.11

---

````

**Comment by vkarpov15** [comment]
@boly38 the issue is in your `package-lock.json`, you have an older version of `@aws-sdk/credential-providers` pinned. A clean install of this repo gives me the following:

```
connect-mongodb-session@3.1.1
└─┬ mongodb@4.17.1
  └─┬ @aws-sdk/credential-providers@3.427.0
    └─┬ @aws-sdk/client-sts@3.427.0
      └── fast-xml-parser@4.2.5
```

**Comment by angelhdzmultimedia** [comment]
> @boly38 the issue is in your `package-lock.json`, you have an older version of `@aws-sdk/credential-providers` pinned. A clean install of this repo gives me the following:
> 
> ```
> connect-mongodb-session@3.1.1
> └─┬ mongodb@4.17.1
>   └─┬ @aws-sdk/credential-providers@3.427.0
>     └─┬ @aws-sdk/client-sts@3.427.0
>       └── fast-xml-parser@4.2.5
> ```

Thank you will try by removing the lock file.

**Comment by vkarpov15** [comment]
This package, as currently written, won't work with `mongodb@6`, because that version dropped callback support.

**Comment by angelhdzmultimedia** [comment]
> This package, as currently written, won't work with `mongodb@6`, because that version dropped callback support.

![image](https://github.com/mongodb-js/connect-mongodb-session/assets/10191085/355df8f9-5055-410f-ade8-c8061a38d440)

![image](https://github.com/mongodb-js/connect-mongodb-session/assets/10191085/0e4152a4-59de-470d-8251-23c46aa0ebc3)

Anyways, I don't remember why I needed to fork this package. The one I really wanted to fork was express-session so I can open a PR to add async functions (session.update, session.destroy, session.save, etc.)

Today I'm working on a new Nuxt project, and will need this package, so if I remember what I was trying to contribute with, I will reopen this issue.

Thank you everyone for your time and kindness.
Wishing you all health, peace, and success.

**Comment by boly38** [comment]
>@boly38 the issue is in your package-lock.json, you have an older version of @aws-sdk/credential-providers pinned
Yep U right, sorry for my mistake, my bad !

>This package, as currently written, won't work with mongodb@6, because that version dropped callback support.
I had exactly this issue while trying locally to update dep tree with mongo 6.x because of mongo client constructor .. ok :)

Thanks again @angelhdzmultimedia and @vkarpov15 (all is fine with `connect-mongodb-session` on my side now) 👍
