### ISSUE TITLE
README references done() multiple times with no definition

### ISSUE THREAD

**Issue by taxilian** [mongodb-js/connect-mongodb-session#16]
In your README there are lots of places where it calls done() but I don't see anywhere that is defined....

**Comment by vkarpov15** [comment]
That's because the docs are generated with https://github.com/vkarpov15/acquit, so the examples are actual test cases. I can see how that would be confusing though, so https://github.com/vkarpov15/acquit/issues/5

**Comment by vkarpov15** [comment]
For general interest in case anybody wants an acquit plugin to help with this: https://www.npmjs.com/package/acquit-ignore
