### ISSUE TITLE
Change wget to curl in setup-test.sh?

### ISSUE THREAD

**Issue by analog-nico** [mongodb-js/connect-mongodb-session#19]
On my MacOS X system wget is not available. But curl is. Thus setup-test.sh works with:
``` sh
curl -OL https://github.com/strongloop/express/archive/3.18.1.tar.gz
```

AFAIK curl is more commonly available than wget in *nix distributions. Maybe it makes sense switching to curl. However, I am not too familiar with all that command line stuff...

**Comment by vkarpov15** [comment]
`curl -OL` works too. I've been blissfully mac-free for most of this year so I didn't notice :)
