### ISSUE TITLE
?replicaSet=foo style urls don't work

### ISSUE THREAD

**Issue by taxilian** [mongodb-js/connect-mongodb-session#20]
Hoping you might have some insight on this one; when I use connect-mongodb-session I pass it the same db config that I use to connect to mongoose.  In one case, that looks like this:

    mongodb://devbox.02.mydomain.com:27017,devbox.01.mydomain.com:27017/mydbname?replicaSet=foo

When I do this, everything works fine in mongoose, but connect-mongodb-session gives me `Error connecting to db: no valid seed servers in list`

Any idea why this isn't working?

**Comment by vkarpov15** [comment]
Hmm are you connecting from the same process as mongoose? Can you actually connect to those boxes from your machine? That error [only occurs when the driver couldn't connect to the boxes or if the repl set is not in a valid state](https://github.com/christkv/mongodb-core/blob/master/lib/topologies/replset.js#L1127-L1144)

**Comment by taxilian** [comment]
I am connecting in the same process; basically the file that connects mongoose passes back the db configuration and about 10 lines later (in terms of actual execution) uses the same URI and options with connect-mongodb-session.

The really weird part is that after submitting this ticket, I found that I can connect just fine if I use the old replicaset syntax:

    mongodb://devbox.02.mydomain.com:27017,mongodb://devbox.01.mydomain.com:27017/mydbname

As soon as I add `?replicaSet=foo` it stops working, but the other one works fine.  Same process.  I'm completely baffled, was hoping you'd have an idea :-/

**Comment by vkarpov15** [comment]
What do your connection options look like? Also, are you sure the replicaSet specified in the URI matches the replica set name?

**Comment by taxilian** [comment]
Exactly like the examples in this ticket; I changed hostnames and replicaset names, but that's it.  Yes, I'm absolutely certain that the replicaset name matches; I spent 30 minutes trying every possible thing I could think of, so those are the first things I checked =]

The other things that are passed in as options are SSL certificates and we set the poolSize.  The condensed code looks roughly like this:

    var dbURI = "mongodb://devbox.02.mydomain.com:27017,devbox.01.mydomain.com:27017/mydbname?replicaSet=foo";

    var mongoCert = fs.readFileSync("/path/to/ssl_crt"));
    var mongoKey  = fs.readFileSync("/path/to/ssl_key"));
    var mongoCA   = fs.readFileSync("/path/to/ssl_ca"));
    var opts = {
        replSet: {
            ssl:true,
            sslKey: mongoKey,
            sslCert: mongoCert,
            sslCA: mongoCA,
            socketOptions: {},
            poolSize: 5
        }
    };
    
    // Connect with mongoose; this works
    mongoose.connect(dbURI, opts);

    // Configure the session store, this does not work
    var mongoSessionStore = new MongoDBStore({
        uri: dbURI,
        connectionOptions: opts,
        collection: 'sessions2'
    });

**Comment by vkarpov15** [comment]
I think you may want to use:

```javascript
var opts = {
    replSet: {
        ssl:true,
        sslKey: mongoKey,
        sslCert: mongoCert,
        sslCA: mongoCA,
        socketOptions: {}
    },
    server: {
        ssl:true,
        sslKey: mongoKey,
        sslCert: mongoCert,
        sslCA: mongoCA,
        socketOptions: {}
    }
};
```

mongoose does a little extra syntactic sugar on top of options so you don't have to worry about replSet options vs server options, whereas connect-mongodb-session just goes to the driver directly.

**Comment by taxilian** [comment]
Well that's really weird; I used to always pass replSet, server, and mongos objects in there, but when I did it broke the mongoose connection, so I started detecting a replicaSet url in my config and removed the other two in that case; maybe I just needed to remove mongos?  I'll try it.

**Comment by vkarpov15** [comment]
That's really strange. I generally try to specify everything in the connection string where possible, but unfortunately things like `sslKey`, etc. are not supported in the mongodb driver's connection string parser at the moment... Try removing mongos, that may help.

**Comment by taxilian** [comment]
this is working; I honestly don't remember what all it was. =] I think it may have been the whole replset vs replSet thing.
