### ISSUE TITLE
Missing "main" in package.json file.

### ISSUE THREAD

**Issue by lagay** [mongodb-js/connect-mongodb-session#22]
I am using Node 4.2.3, Sails 0.11.4, and connect-mongodb-session 1.1.0. While using connect-mongodb-session as a session storage I ran into an error.

I am setting the following options within the config/session.js file.
```
module.exports.session = {
  adapter: 'connect-mongodb-session',
  uri: mongodb-uri,
  connectionOptions: {
    ssl: true,
    replSet: mongodb-replSet,
    db: mongodb-name
  }
};
```
I lift the app and get the following error.

```
Could not load Connect session adapter :: connect-mongodb-session
(If this is your module, make sure that the module has a "main" configuration in its package.json file)

TypeError: Path must be a string. Received undefined
/sails/lib/hooks/session/index.js:129
```
https://github.com/balderdashy/sails/blob/v0.11.4/lib/hooks/session/index.js

So I added the following to the connect-mongodb-session package.json and no longer get the error.
`
"main": "index"
`
Can you add this line to your package.json file please?

Also, in your readme, I don't see any examples of how to use this module within the config/session.js file. I had to search through the code to determine how to setup the values to be passed to the session adapater. Maybe add this as an example within the readme. The main reason I went with this module instead of connect-mongo was due to the support of the replSet. :+1: 

Example:
config/session.js

```
module.exports.session = {
  adapter: 'connect-mongodb-session',
  uri: mongodb-uri,
  connectionOptions: {
    ssl: true,
    replSet: mongodb-replSet,
    db: mongodb-name
   }
};
```

**Comment by vkarpov15** [comment]
Fixed and released 1.1.1, sorry for the delay. Re: example for how to use this with sails, I have zero experience with sails, but you're more than welcome to contribute one: https://github.com/mongodb-js/connect-mongodb-session/blob/master/test/examples.test.js
