### ISSUE TITLE
resave option

### ISSUE THREAD

**Issue by matteocontrini** [mongodb-js/connect-mongodb-session#24]
Hi,
on the express-session module readme, I can read that the `resave` option should be set according to what the store supports.

In particular:

> The best way to know is to check with your store if it implements the  touch  method. If it does, then you can safely set  resave: false . If it does not implement the  touch  method and your store sets an expiration date on stored sessions, then you likely need  resave: true .

Given that I have no idea of what the touch method is (it's not explained that well...), what value do you recommend setting for `saved`?

Thanks.

**Comment by matteocontrini** [comment]
Up

**Comment by vkarpov15** [comment]
Added to docs: https://github.com/mongodb-js/connect-mongodb-session#it-can-store-sessions-for-express-4 . Long story short, I'd recommend using the defaults, `resave: true` and `saveUninitialized: true`, unless you have a reason not to.

**Comment by Lichtjaeger** [comment]
Both defaults are deprecated and "will change in the future". So please put these options to your docs.

The reasons are writen in the docs of "express-session":

resave:
> Depending on your store this may be necessary, but it can also create race conditions where a client makes two parallel requests to your server and changes made to the session in one request may get overwritten when the other request ends, even if it made no changes (this behavior also depends on what store you're using).

saveUninitialized:
> Choosing false is useful for implementing login sessions, reducing server storage usage, or complying with laws that require permission before setting a cookie. Choosing false will also help with race conditions where a client makes multiple parallel requests without a session.

If this insn't a problem with MongoDB, I'm a even more happy user. :)
