### ISSUE TITLE
Request: Please make a "koa-mongodb-session" module

### ISSUE THREAD

**Issue by Lichtjaeger** [mongodb-js/connect-mongodb-session#25]
Hi,

I'm working on subdomains with servers for each domain. Most of them working with express 4 and your session store. The session is shared between all subdomains (domain cookie).

But I want to switch from express 4 to koa 2. The problem now: the session stores for [koa sessions](https://www.npmjs.com/package/koa-generic-session) use an other scheme and that conflicts with yours.

It would by nice if there were also a "koa-mongodb-session" module of you, so I can bring my koa and express servers together.

**Comment by vkarpov15** [comment]
There are a couple modules out there already: https://www.npmjs.com/search?q=koa+mongodb although I imagine they don't support koa 2. They'd be a good starting point, but unfortunately I don't think I'll have the time to build one for at least the next several months. Appreciate the suggestion though, I didn't know that koa 2 was already out.

**Comment by Lichtjaeger** [comment]
That's a pity.

I allready have a working [mongoDB session store](https://github.com/pavelvlasov/koa-generic-session-mongo) for koa. The problem is still: it uses another scheme.

The shared cookie get resolved to the wrong/non existent documents on the other famework (both directions).

It would be nice if there were interchangeable solutions, collected under you organization.

Perhaps I could build the module on my own, if I find the time.

**Comment by Lichtjaeger** [comment]
It was easier then I thought. I have the "[koa-mongodb-session](https://github.com/Lichtjaeger/koa-mongodb-session)" ready and working. If you want to have it, I can send you a PR or transfere ownership.

But I found a even better solution. I can use the "express-session"-module with "connect-mongodb-session" if I use the "[koa-connect](https://github.com/vkurchatkin/koa-connect/tree/vNext)" middleware-bridge.
That works for me.

**Comment by vkarpov15** [comment]
Glad you figured it out. It's all yours, you wrote it, I barely even use koa :)
