### ISSUE TITLE
How to import connect-mongo (session) in ES6?

### ISSUE THREAD

**Issue by lautiamkok** [mongodb-js/connect-mongodb-session#26]
In pre-ES6, this is how I import `connect-mongo` (session):

    `var MongoStore = require("connect-mongo")(session);`

But how can I import it in ES6?

   ```
 import MongoStore from 'connect-mongo';
 let monStore = MongoStore(session);

```
Error:

    ```
    const Store = connect.Store || connect.session.Store;
                                                      ^
    TypeError: Cannot read property 'Store' of undefined

   ```
Any ideas?

**Comment by guptapriyanshu7** [comment]
import MongoDBStore from "connect-mongodb-session";
const MongoStore = MongoDBStore(session);
const store = new MongoStore({
  uri: uri,
  collection: "sessions",
});
