### ISSUE TITLE
Expiring unused sessions after 10 minutes on inactive

### ISSUE THREAD

**Issue by serganus** [mongodb-js/connect-mongodb-session#27]
I am trying to find a way to expire unused sessions after 10 minutes of inactive usage. Any help would be appreciated.

**Comment by vkarpov15** [comment]
2 options:

1) Use this module's `expires` option:

```javascript
var store = new MongoDBStore({ expires: 25 });
app.use(session);
```

2) Create a [TTL index in mongodb](https://docs.mongodb.com/manual/core/index-ttl/). This module doesn't have the ability to build a TTL index for you, so you'd have to do it yourself.

**Comment by serganus** [comment]
@vkarpov15 Using option (1)/(2) would expire all sessions after 25 seconds or the uninitialized ones?

**Comment by vkarpov15** [comment]
All sessions. Sorry, didn't read carefully. No way to do that as far as I know. Easiest way would to use setinterval to delete unused sessions
