### ISSUE TITLE
How to revive after an initial connection error?

### ISSUE THREAD

**Issue by cadilhac** [mongodb-js/connect-mongodb-session#31]
Hi,

Even if the database is down, I would like to have a live website showing a connection error. Right now, the node server just hangs when mongoose can't connect. I have added an error callback in the MongoDBStore constructor so that it doesn't throw. But then the server hangs and no page can be served. If I remove the store property from the app.use(session(...)) call then all goes back to normal for serving pages which seems to prove that mongoose is the blocker here.
What should I do?

Thanks

**Comment by caub** [comment]
you can start your server once the connection is done, with Mongoose I don't know, but with the mongodb driver it's simple

**Comment by vkarpov15** [comment]
So if initial connection fails there's really no way for the store to recover. If you're sure you don't want to throw when initial connection fails, you can instead add a custom middleware that returns an error page if the MongoDBStore constructor errored out. But in my experience the "crash if initial connection fails" approach is usually the right one.
