### ISSUE TITLE
not working with authentication enabled on mongo

### ISSUE THREAD

**Issue by grkblood13** [mongodb-js/connect-mongodb-session#44]
I'm running mongodb 3.2.13. When I enable authentication on mongo I get the following error when using this module.

/usr/local/node-farm/deps/connect-mongodb-session/node_modules/mongodb/lib/utils.js:123
    process.nextTick(function() { throw err; });
                                  ^

Error: Error creating index: not authorized on test to execute command { listIndexes: "sessions", cursor: {} }
    at /usr/local/node-farm/deps/connect-mongodb-session/index.js:53:21
    at handleCallback (/usr/local/node-farm/deps/connect-mongodb-session/node_modules/mongodb/lib/utils.js:120:56)
    at /usr/local/node-farm/deps/connect-mongodb-session/node_modules/mongodb/lib/db.js:1155:46
    at /usr/local/node-farm/deps/connect-mongodb-session/node_modules/mongodb/lib/db.js:1580:20
    at handleCallback (/usr/local/node-farm/deps/connect-mongodb-session/node_modules/mongodb/lib/utils.js:120:56)
    at /usr/local/node-farm/deps/connect-mongodb-session/node_modules/mongodb/lib/cursor.js:857:22
    at handleCallback (/usr/local/node-farm/deps/connect-mongodb-session/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:171:5)
    at /usr/local/node-farm/deps/connect-mongodb-session/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:585:22
    at queryCallback (/usr/local/node-farm/deps/connect-mongodb-session/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:212:16)
    at /usr/local/node-farm/deps/connect-mongodb-session/node_modules/mongodb/node_modules/mongodb-core/lib/connection/pool.js:469:18
~

Everything seems to work fine when I turn authentication off. Unfortunately thats not an option for me.

**Comment by vkarpov15** [comment]
Hard to tell without more info, but here's some questions you can ask yourself to help resolve this issue:

1) Can you connect using the `mongo` shell using the options specified in `mongo --help`? If not, you probably created your user on the wrong database, so please read up on [createUser](https://docs.mongodb.com/manual/reference/method/db.createUser/)
2) Are you specifying your auth credentials in your connection string correctly? That is, are you doing `mongodb://username:password@hostname:port/db`?
3) Can you check if your user has [read permissions for that db and collection](https://docs.mongodb.com/manual/reference/command/listIndexes/#required-access)? Specifically, can you run `db.sessions.listIndexes()` from the mongodb shell if you're logged in as that user?

If none of these is the case, it might be a bug in this lib, but this seems like a permissions configuration issue.

**Comment by bijoythomas** [comment]
If the problem persists after verifying all the steps that @vkarpov15 listed above, then its possible you are running into a driver issue like: https://jira.mongodb.org/browse/NODE-719

In my case, the logs had messages like: 
**SCRAM-SHA-1 authentication failed
Unmatched SCRAM-SHA-1 nonce received from client in second step**

**Comment by ilyabozhkov** [comment]
In my case I had to create a user specifically for this one database. The users that I create within "admin" database, even with "root" roles fail to authenticate. So I had to
`$ mongo`
`>use MySessionsDatabase`
`>db.createUser({user: "user_that_limited_to_the_MySessionsDatabase", pwd: "mypassword", roles: [ "readWrite" ]})`

Just to make sure that the user actually exists within that specific database (MySessionsDatabase):
`>use MySessionsDatabase`
`>db.getUsers()`. 

If the user you just created is there - then the authentication (for that user) doesn't fail.

**Comment by qodesmith** [comment]
I'm having issues connecting with authentication as well. When I connect via the `mongo` command, I do something like this:

```mongo --port <port num> -u myUserName -p myPassword```

This connects successfully. To create a MongoStore, I'm trying to put the username and pw into the url string but it keeps failing (I'm using the same credentials as above):

```javascript
const store = new MongoStore({
  uri:`mongodb://${myUserName}:${myPassword}@localhost:${mongoPort}/${dbName}`,
  collection: 'myCollection'
}, err => console.log('MONGO STORE ERROR:', err))
```

Any thoughts? Any other way to pass credentials?

**Comment by vkarpov15** [comment]
@qodesmith double check that your `dbName` is correct. When you run `mongo --port <port num> -u myUserName -p myPassword` you're connecting to the `test` database.

Also, try using `encodeURIComponent()`: `mongodb://${encodeURIComponent(myUserName)}:${encodeURIComponent(myPassword)}@localhost:${mongoPort}/${dbName}`

**Comment by NetOperatorWibby** [comment]
I just added authentication to my database and surprise, ran into this issue.
