### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by amihailes** [mongodb-js/connect-mongodb-session#46]
Hi,
When used with mongoose, the message in the console:

DeprecationWarning: 'ensureIndex()' is deprecated in Mongoose >= 4.12.0, use 'createIndex()' instead

nodejs 6.11.4
mongoose : 4.12.0
mongodb 3.4.9

It seems that ensureIndex in the code must be replaced by createIndex.

Thanks

**Comment by AO19** [comment]
You can achieve this by giving the connect method the needed parameter:  
```
mongoose.connect(process.env.DATABASE, {
  useNewUrlParser: true,
  useCreateIndex: true,
});
```
