### ISSUE TITLE
Expected an assignment or function call

### ISSUE THREAD

**Issue by LaKing** [mongodb-js/connect-mongodb-session#56]
My JS linter complains on `store.client`

```javascript
store.on('connected', function() {
  store.client; // The underlying MongoClient object from the MongoDB driver
});
```

Actually, since I'm new to connect-mongodb-session, I'm not sure if this is a real issue, or .. ?

**Comment by vkarpov15** [comment]
The `store.client;` bit is just an example, you don't really need that line or even `store.on('connected')` in general. Will add a comment about that in the docs.

**Comment by LaKing** [comment]
Oh I understand. I would suggest to modify it to 
```javascript
store.on('connected', function() {
  console.log(store.client); // The underlying MongoClient object from the MongoDB driver
});
```

**Comment by vkarpov15** [comment]
I just removed it. That's really something that belongs in API docs, not a first example, because it isn't necessary to get up and running with this module.
