### ISSUE TITLE
Deprecation Warning: collection.remove

### ISSUE THREAD

**Issue by ramicohen303** [mongodb-js/connect-mongodb-session#59]
When a session is destroyed, the following warning is logged: DeprecationWarning: collection.remove is deprecated. Use deleteOne, deleteMany, or bulkWrite instead.

**Comment by ramicohen303** [comment]
Can someone please review this pull request and let me know if I need to change something?

**Comment by vkarpov15** [comment]
@ramicohen303 thanks for your patience, I fell behind on emails for a while. I merged your PR.

**Comment by ramicohen303** [comment]
Thank you
