### ISSUE TITLE
Regression in 2.0.8: databaseName no longer working

### ISSUE THREAD

**Issue by ramicohen303** [mongodb-js/connect-mongodb-session#64]
Until 2.0.7, sending the databaseName property was working properly. Starting with 2.0.8, the exception "Uncaught MongoError: database name must be a string" is thrown. Passing the database name in the Url parameter works fine like before.

Looks like the databaseName property is missing from the new archetype validation.

**Comment by vkarpov15** [comment]
Fixed and released 2.1.1 :+1:

**Comment by ramicohen303** [comment]
Thank you
