### ISSUE TITLE
Upgrade to mongodb 3.2.1 

### ISSUE THREAD

**Issue by ZhangYiJiang** [mongodb-js/connect-mongodb-session#68]
I'm trying to reduce the number of MongoDB drivers installed in my application. Currently connect-mongodb-session is tracking 3.1.x because it uses `~3.1.7`, while Mongoose is using 3.2.x. Is there any reason for tracking only the latest patch version, and is it possible to get a new release that tracks the 3.2.x branch? Many thanks!

**Comment by vkarpov15** [comment]
Just released v2.2.0, that uses mongodb@3.2.x :+1:
