### ISSUE TITLE
Upgrade to MongoDB 3.3.x

### ISSUE THREAD

**Issue by saltire** [mongodb-js/connect-mongodb-session#69]
Just a notice that the `mongodb` driver has released version `3.3.0`, if you are interested in supporting it :)

**Comment by tirmey** [comment]
This module will support mdb 3.3 in the near future?

**Comment by vkarpov15** [comment]
@tirmey sorry for the late response. We recently release v2.3.0 of this module, which uses `mongodb@3.5`
