### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by tbhaxor** [mongodb-js/connect-mongodb-session#79]
I would appreciate if anyone could fix this issue

```
(node:25954) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
```

**Comment by phongvu99** [comment]
If you really want to get rid of it then pass the options object when you're connecting to the database like this:
const URI = 'yourMongoDBURIhere';
mongoose.connect(URI, {
        useNewUrlParser: true,
        useUnifiedTopology: true
})...
Here I'm using 'mongoose' but generally, the syntax wouldn't change much.

**Comment by tbhaxor** [comment]
@phongvu99  THANKS, I ll try this one too
