### ISSUE TITLE
How to use an existing mongoose connection

### ISSUE THREAD

**Issue by nickgarver** [mongodb-js/connect-mongodb-session#92]
How could I connect to mongo using an existing mongoose connection, similar to this example in connect-mongo.

```
const mongoose = require('mongoose');

// Basic usage
mongoose.connect(connectionOptions);

app.use(session({
    store: new MongoStore({ mongooseConnection: mongoose.connection })
}));
```

**Comment by vkarpov15** [comment]
That functionality is intentionally omitted from this module, we recommend creating a new connection for this module to avoid [slow trains](https://thecodebarbarian.com/slow-trains-in-mongodb-and-nodejs)
